template: GPSTracker, %s!

server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9099

tcpServerPort: 9090

logging:
  loggers:
    example: DEBUG
