template: GPSTracker, %s!

defaultName: Stringer

server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9099

logging:
  loggers:
    example: DEBUG
