template: GPSTracker, %s!

server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9099

tcpServerPort: 9090

jmsHost: 127.0.0.1
jmsPort: 5445
jmsQueueName: trackerQueue
jmsQueueRecordKey: trackerUpdate

logging:
  loggers:
    example: DEBUG
